export const INITIAL_FETCH_PRODUCTS = 'INITIAL_FETCH_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const CURRENTPAGE_UPDATE = 'CURRENTPAGE_UPDATE';
